<?php
/* m3-build.php — bakes vendor/m3/tokens.css from the M3 Expressive component set.
   Run by hand, never in a request:  php m3-build.php

   **Why this exists.** Every M3 number in this app used to be hand-copied into `css/base.css` from
   a component file on GitHub. That is a transcription, and a transcription drifts. This app is going
   to take more M3 components, so the token scales come from the source instead.

   **The source is bczak/m3you**, MIT licensed, the same repo `css/chrome.css` already cites for the
   dialog, the side sheet, the bottom sheet and the app bar. Its `src/styles/tokens/` holds plain CSS
   custom properties, so nothing here needs React, a bundler or a build step at request time.

   **Colour is deliberately NOT baked.** `sys.color.css` and `sys.color.dark.css` carry M3's full
   tonal palette, and this app declines it. Two rules in CLAUDE.md say why. The traffic-light ladder
   is reserved for status, and this app holds ONE surface tone rather than M3's five containers.
   `css/base.css` maps the `--md-sys-color-*` names a vendored component asks for onto the tokens
   this app already has. That map is this app's own work, so it lives in this app's own file.

   **The typescale names two typefaces and this app vendors neither.** `--md-ref-typeface-brand` and
   `-plain` both resolve to "Roboto Flex", "Roboto", system-ui. Nothing here sets `font-family` from a
   token, so those two are inert. A vendored component that does reach for one falls back to Roboto,
   which `vendor/fonts.css` does carry.

   Refresh: run this, check the diff, and bump `vendor/m3/tokens.css?v=` in index.html. */

const REPO = 'https://raw.githubusercontent.com/bczak/m3you/development/src/styles/tokens/';

/* Order is `_index.css`'s own, less the two colour files. Each scale is independent, so the order
   is documentation rather than a dependency. */
const FILES = ['sys.shape.css', 'sys.typescale.css', 'sys.elevation.css', 'sys.motion.css',
               'sys.state.css'];

$out = "/* GENERATED by m3-build.php. Do not edit. Run `php m3-build.php` to refresh.\n"
     . "   M3 Expressive design tokens, from bczak/m3you (MIT), src/styles/tokens/.\n"
     . "   Colour is not here on purpose — see the header of m3-build.php, and the bridge in\n"
     . "   css/base.css that maps M3's colour names onto this app's own palette. */\n";

foreach (FILES as $f) {
    $c = curl_init(REPO . $f);
    curl_setopt_array($c, [CURLOPT_RETURNTRANSFER => 1, CURLOPT_TIMEOUT => 20,
                           CURLOPT_FOLLOWLOCATION => 1]);
    $body = curl_exec($c);
    $code = curl_getinfo($c, CURLINFO_HTTP_CODE);
    curl_close($c);

    /* A 404 answers with a body, so the status has to be checked. A silent miss here bakes a token
       file with a scale missing, and every rule that reads that scale falls back to its initial
       value — which is usually nothing at all, and errors nowhere. */
    if ($code !== 200 || trim($body) === '') {
        fwrite(STDERR, "FAILED $f (HTTP $code)\n");
        exit(1);
    }
    $out .= "\n/* ---- $f ---- */\n" . rtrim($body) . "\n";
    fwrite(STDERR, sprintf("  %-22s %6d bytes\n", $f, strlen($body)));
}

@mkdir(__DIR__ . '/vendor/m3', 0777, true);
file_put_contents(__DIR__ . '/vendor/m3/tokens.css', $out);
printf("wrote vendor/m3/tokens.css, %d bytes\nBump vendor/m3/tokens.css?v= in index.html.\n",
       strlen($out));
